"""initial complaints schema

Hand-written rather than autogenerated, because the enum creation order and the pgcrypto
extension both matter and autogenerate gets neither right on a first run.

Reversible: downgrade() drops the table and then the enum types, in that order, because a
type cannot be dropped while a column still uses it.

Revision ID: 0001_initial
Revises: None
Create Date: 2026-09-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CATEGORY = ("water", "electricity", "sanitation", "roads", "streetlights", "other")
PRIORITY = ("high", "normal", "low")
STATUS = ("open", "in_progress", "resolved", "rejected")
TRIAGED_BY = ("llm:groq", "llm:ollama", "rules", "rules:fallback", "simulated")


def upgrade() -> None:
    # gen_random_uuid() lives in pgcrypto on PG < 13 and in core from 13 onwards; creating
    # the extension is harmless on 16 and makes the migration portable backwards.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # Create the types explicitly, then reference them with create_type=False below.
    # Without that flag create_table() emits CREATE TYPE a second time and the migration
    # dies on DuplicateObject — the most common Alembic-on-Postgres trap there is.
    bind = op.get_bind()
    for name, values in (
        ("category", CATEGORY),
        ("priority", PRIORITY),
        ("status", STATUS),
        ("triaged_by", TRIAGED_BY),
    ):
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    category = postgresql.ENUM(*CATEGORY, name="category", create_type=False)
    priority = postgresql.ENUM(*PRIORITY, name="priority", create_type=False)
    status = postgresql.ENUM(*STATUS, name="status", create_type=False)
    triaged_by = postgresql.ENUM(*TRIAGED_BY, name="triaged_by", create_type=False)

    op.create_table(
        "complaints",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("reporter_contact", sa.String(length=200), nullable=True),
        sa.Column("category", category, nullable=False),
        sa.Column("priority", priority, nullable=False),
        sa.Column("status", status, nullable=False, server_default="open"),
        sa.Column("ai_summary", sa.String(length=140), nullable=True),
        sa.Column("triaged_by", triaged_by, nullable=False),
        sa.Column("triage_latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("seed_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # Length rules enforced in the DB as well as in Pydantic (§2.3): the API is not the
        # only writer.
        sa.CheckConstraint("char_length(text) BETWEEN 10 AND 2000", name="ck_complaints_text_len"),
        sa.CheckConstraint(
            "char_length(location) BETWEEN 3 AND 200", name="ck_complaints_location_len"
        ),
        sa.CheckConstraint("char_length(ai_summary) <= 140", name="ck_complaints_summary_len"),
        sa.CheckConstraint("triage_latency_ms >= 0", name="ck_complaints_latency_nonneg"),
        # The seed's idempotency guarantee: a second run collides here instead of inserting.
        sa.UniqueConstraint("seed_key", name="uq_complaints_seed_key"),
    )

    # Serves the dashboard's list query: WHERE status = ? [AND priority = ?] — the operator's
    # default view is "open, highest priority first", and this is the composite that answers
    # it without a sequential scan.
    op.create_index("ix_complaints_status_priority", "complaints", ["status", "priority"])

    # Serves ORDER BY created_at DESC for pagination, and the created_at range scan behind
    # /api/stats.
    op.create_index("ix_complaints_created_at", "complaints", ["created_at"])


def downgrade() -> None:
    op.drop_index("ix_complaints_created_at", table_name="complaints")
    op.drop_index("ix_complaints_status_priority", table_name="complaints")
    op.drop_table("complaints")

    # Types after the table: a type cannot be dropped while a column still uses it.
    bind = op.get_bind()
    for name in ("triaged_by", "status", "priority", "category"):
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
